# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fade68eb499ea9e273947f39bdbd94a4f0dc339543ff70a61a544658e33764fb1ae6fe23bb92001333e1219c1d3353a6da0cf27b20200d4c2327b9f0640a82ce

test:
  secret_key_base: d76ff7d57aaaf240839f74173bdbd9c8d220b40ed9e2901f71a044a86d70d96823606eb0605a36a86cbc1dfb74bdf67c45ea6595700354d04e39a723bdb4d601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
